### ISSUE TITLE
Remember Me Disabled Still Remembering

### ISSUE THREAD

**Issue by emclaug2** [brightlayer-ui/react-workflows#126]
#### Describe the bug
If I do not select "Remember Me", when I log out my email is remembered.

#### What is the expected behavior?
My email  / password should not be auto-entered after I log out.

#### What are the steps to reproduce?
1. Login without the Remember Me option enabled.
2. Log out.

#### Screenshots or links to minimum reproduction example
![Login Out](https://user-images.githubusercontent.com/6538289/175540372-8045081b-992b-40c7-af51-193ad0dfbc5c.gif)

#### Environment

Chrome Windows	
	
#### Anything else to add?
No

**Comment by emclaug2** [comment]
Is this because my login info is saved by the browser?

**Comment by daileytj** [comment]
@joebochill tested this locally and it is working as expected
