### ISSUE TITLE
Update integration section of the readme

### ISSUE THREAD

**Issue by jeffvg** [brightlayer-ui/react-workflows#128]
#### Describe the bug
The Integration section of the readme states that the example project is in the package and should link out the the workflow example folder instead.

- You have two options for using this package in your application. You can manually integrate the package into an existing project, ***or you can start a project using the /example project provided in the package.***

#### What are the steps to reproduce?
1. Go to...
2. Click on...

**Comment by joebochill** [comment]
Fixed by removing the reference to 'in the package'. The rest of the instructions and the detailed guide for using the example project all make sense.
