### ISSUE TITLE
Don't disable the log in button when browser auto-populates the password

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/react-workflows#43]
#### Describe the bug

A lot of times, a user may have a browser save their login credentials, and the moment they visit the `/login` page, the text fields are populated with login credentials automatically, but the button stays disabled

#### What is the expected behavior?

On page load, there should be an initial check of form validation to enable / disable the login button.

#### What are the steps to reproduce?
1. `npx -p @pxblue/cli pxb new react --name testauth --template authentication --lint --prettier --language=typescript`
2. Log in, have the "remember me" checked
3. When prompted by browser, save the password & credentials
4. Log out
5. If the browser pre-populate your credentials, you will observe that the login button is disabled

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/116592648-39c7a480-a8ee-11eb-9e1a-a82133dc637d.png)

#### Environment

MacOS Chrome
#### Anything else to add?

I didn't check Angular. Pls double check ng's behavior.

**Comment by andrupu** [comment]
Let's check this out in different browsers and see what events are getting executed.  Let's also not forgot to do the same for Angular.  If you want to check out RN go for it.

**Comment by daileytj** [comment]
Tried to fix this issue with the solution presented here https://flaviocopes.com/react-form-browser-autofill/. However, we never have access to the passwordRef value to update state so this doesn't work. 

This has been an issue with browsers for a while and may just be a security issue that will never allow us to handle this gracefully.

Here's another link discussing the issue...
https://bugs.chromium.org/p/chromium/issues/detail?id=352527

**Comment by joebochill** [comment]
Similar to the angular issue, I'm going to close this for now since its an intended browser-security feature. If it becomes a problem in the future we can see about revisiting it.
