### ISSUE TITLE
Switch to more size-efficient import syntax

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-workflows#85]
#### Describe the bug
When using our library in a project, all of the Material-UI components are included in the bundle even if they are never used.

#### What is the expected behavior?
Only the components that are being used should be part of the final bundle

#### What are the steps to reproduce?
1. Create a new authentication project with the CLI
2. Run the build command
3. Use a bundle analyzer to see that _all_ of the Material-UI components code is included in the final bundle, even the more obscure ones.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/133439957-7e9679c9-62ce-41f0-8d69-90337caf927e.png)
		
#### Anything else to add?
This is reported by the Green team. This is something we need to be especially careful about, because a single instance of importing from the root will cause every component to be part of the bundle.

We need to update our component import syntax to use default exports instead of named exports from the index/barrel (i.e., we should not import anything from '@material-ui/core' in our library:

https://material-ui.com/guides/minimizing-bundle-size/#option-1

**Comment by joebochill** [comment]
I know we recently fixed this in another repository? Might've been this one and we just need to confirm it.

**Comment by emclaug2** [comment]
Fixed in #101
