### ISSUE TITLE
Update to latest dependencies

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/react-workflows#97]
#### Describe the desired behavior
Use the most recent version of dependencies

#### Describe the current behavior
Using some outdated dependencies

#### Is this request related to a current issue?
No

#### Additional Context

Be particularly careful with updating these as there are compatibility consideration to account for. Test this VERY thoroughly as you go along to make sure that there are no regressions or other unintended consequences.

**Comment by ektasawant** [comment]
https://github.com/brightlayer-ui/react-workflows/pull/113 merged. Closing this issue.
